/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Settings = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	websiteName?: string;
	introMessage?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
	description?: string;
	socialMedia?: Array<{
		label?: string;
		title?: string;
		url?: string;
		_key: string;
	}>;
};

export type Navigation = {
	_id: string;
	_type: 'navigation';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	items?: Array<{
		title?: string;
		href?: string;
		_key: string;
	}>;
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Post = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type?: 'article' | 'project' | 'page' | 'artwork';
	image?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'lazy' | 'eager';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster?: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'lazy' | 'eager';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
		  }
		| ({
				_key: string;
		  } & Code)
		| ({
				_key: string;
		  } & Table)
	>;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type MediaTag = {
	_id: string;
	_type: 'media.tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Slug;
};

export type Table = {
	_type: 'table';
	rows?: Array<
		{
			_key: string;
		} & TableRow
	>;
};

export type TableRow = {
	_type: 'tableRow';
	cells?: Array<string>;
};

export type Code = {
	_type: 'code';
	language?: string;
	filename?: string;
	code?: string;
	highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| Settings
	| Navigation
	| SanityImageAssetReference
	| SanityFileAssetReference
	| Post
	| SanityImageCrop
	| SanityImageHotspot
	| Slug
	| MediaTag
	| Table
	| TableRow
	| Code
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../frontend/src/app/[slug]/page.tsx
// Variable: postMetadataQuery
// Query: *[_type == "post" && slug.current == $slug][0] {			title,			description,			slug,			image { 	asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background, }		}
export type PostMetadataQueryResult = {
	title: string | null;
	description: string | null;
	slug: Slug | null;
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
} | null;

// Source: ../frontend/src/app/[slug]/page.tsx
// Variable: postPageQuery
// Query: *[_type == "post" && slug.current == $slug][0] {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},	body[] {		...,		_type == 'image' => {			...,			"width": asset->metadata.dimensions.width,			"height": asset->metadata.dimensions.height,			"color": asset->metadata.palette.dominant.background,		},		_type == 'video' => {			...,			"url": file.asset->url,			poster {				asset,				"width": asset->metadata.dimensions.width,				"height": asset->metadata.dimensions.height,			},		},	}		}
export type PostPageQueryResult = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type?: 'article' | 'artwork' | 'page' | 'project';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				_key: string;
				_type: 'code';
				language?: string;
				filename?: string;
				code?: string;
				highlightedLines?: Array<number>;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
				width: number | null;
				height: number | null;
				color: string | null;
		  }
		| {
				_key: string;
				_type: 'table';
				rows?: Array<
					{
						_key: string;
					} & TableRow
				>;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster: {
					asset: SanityImageAssetReference | null;
					width: number | null;
					height: number | null;
				} | null;
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
				url: string | null;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	> | null;
} | null;

// Source: ../frontend/src/app/[slug]/page.tsx
// Variable: postPageOtherPostsQuery
// Query: *[_type == "post" && slug.current != $slug && type == $type][0...16] | order(meta.date desc, _createdAt desc) {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},		}
export type PostPageOtherPostsQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type?: 'article' | 'artwork' | 'page' | 'project';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body?: Array<
		| ({
				_key: string;
		  } & Code)
		| ({
				_key: string;
		  } & Table)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster?: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	>;
}>;

// Source: ../frontend/src/app/[slug]/page.tsx
// Variable: postsStaticParamsQuery
// Query: *[_type == "post"] { slug }
export type PostsStaticParamsQueryResult = Array<{
	slug: Slug | null;
}>;

// Source: ../frontend/src/app/api/feed/[format]/route.ts
// Variable: feedQuery
// Query: *[_type == "post" && type != "page"][0...16] | order(_createdAt desc) {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},	body[] {		...,		_type == 'image' => {			...,			"width": asset->metadata.dimensions.width,			"height": asset->metadata.dimensions.height,			"color": asset->metadata.palette.dominant.background,		},		_type == 'video' => {			...,			"url": file.asset->url,			poster {				asset,				"width": asset->metadata.dimensions.width,				"height": asset->metadata.dimensions.height,			},		},	}		}
export type FeedQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type?: 'article' | 'artwork' | 'page' | 'project';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				_key: string;
				_type: 'code';
				language?: string;
				filename?: string;
				code?: string;
				highlightedLines?: Array<number>;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
				width: number | null;
				height: number | null;
				color: string | null;
		  }
		| {
				_key: string;
				_type: 'table';
				rows?: Array<
					{
						_key: string;
					} & TableRow
				>;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster: {
					asset: SanityImageAssetReference | null;
					width: number | null;
					height: number | null;
				} | null;
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
				url: string | null;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	> | null;
}>;

// Source: ../frontend/src/app/artworks/page.tsx
// Variable: artworksPageQuery
// Query: *[_type == "post" && type == "artwork"] | order(meta.date desc, _createdAt desc) {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},		}
export type ArtworksPageQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type: 'artwork';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body?: Array<
		| ({
				_key: string;
		  } & Code)
		| ({
				_key: string;
		  } & Table)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster?: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	>;
}>;

// Source: ../frontend/src/app/layout.tsx
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]
export type NavigationQueryResult = {
	_id: string;
	_type: 'navigation';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	items?: Array<{
		title?: string;
		href?: string;
		_key: string;
	}>;
} | null;

// Source: ../frontend/src/app/layout.tsx
// Variable: layoutSettingsQuery
// Query: *[_type == "settings"][0] { socialMedia }
export type LayoutSettingsQueryResult = {
	socialMedia: Array<{
		label?: string;
		title?: string;
		url?: string;
		_key: string;
	}> | null;
} | null;

// Source: ../frontend/src/app/page.tsx
// Variable: homeMetadataQuery
// Query: *[_type == "settings"][0] {			websiteName,			description,		}
export type HomeMetadataQueryResult = {
	websiteName: string | null;
	description: string | null;
} | null;

// Source: ../frontend/src/app/page.tsx
// Variable: homeSettingsQuery
// Query: *[_type == "settings"][0] {			introMessage		}
export type HomeSettingsQueryResult = {
	introMessage: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href?: string;
			_type: 'link';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}> | null;
} | null;

// Source: ../frontend/src/app/page.tsx
// Variable: homeArtworksQuery
// Query: *[_type == "post" && type == "artwork"][0...16] | order(meta.date desc, _createdAt desc) {					...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},	"thumbnailVideoUrl": thumbnailVideo.asset->url,		}
export type HomeArtworksQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type: 'artwork';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body?: Array<
		| ({
				_key: string;
		  } & Code)
		| ({
				_key: string;
		  } & Table)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster?: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	>;
	thumbnailVideoUrl: string | null;
}>;

// Source: ../frontend/src/app/page.tsx
// Variable: homePostsQuery
// Query: *[_type == "post" && type == "article"][0...16] | order(meta.date desc, _createdAt desc) {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},		}
export type HomePostsQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type: 'article';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body?: Array<
		| ({
				_key: string;
		  } & Code)
		| ({
				_key: string;
		  } & Table)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster?: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	>;
}>;

// Source: ../frontend/src/app/page.tsx
// Variable: homeProjectsQuery
// Query: *[_type == "post" && type == "project"][0...16] | order(meta.date desc, _createdAt desc) {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},		}
export type HomeProjectsQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type: 'project';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body?: Array<
		| ({
				_key: string;
		  } & Code)
		| ({
				_key: string;
		  } & Table)
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster?: {
					asset?: SanityImageAssetReference;
					media?: unknown;
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	>;
}>;

// Source: ../frontend/src/app/projects/page.tsx
// Variable: projectsPageQuery
// Query: *[_type == "post" && type == "project"] | order(meta.date desc, _createdAt desc) {				...,	image {			asset,	alt,	"width": asset->metadata.dimensions.width,	"height": asset->metadata.dimensions.height,	"color": asset->metadata.palette.dominant.background,	},	body[] {		...,		_type == 'image' => {			...,			"width": asset->metadata.dimensions.width,			"height": asset->metadata.dimensions.height,			"color": asset->metadata.palette.dominant.background,		},		_type == 'video' => {			...,			"url": file.asset->url,			poster {				asset,				"width": asset->metadata.dimensions.width,				"height": asset->metadata.dimensions.height,			},		},	}		}
export type ProjectsPageQueryResult = Array<{
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	type: 'project';
	image: {
		asset: SanityImageAssetReference | null;
		alt: null;
		width: number | null;
		height: number | null;
		color: string | null;
	} | null;
	thumbnailVideo?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	description?: string;
	meta?: {
		agency?: string;
		client?: string;
		date?: string;
	};
	body: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: 'span';
					_key: string;
				}>;
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal';
				listItem?: 'bullet' | 'number';
				markDefs?: Array<{
					href?: string;
					_type: 'link';
					_key: string;
				}>;
				level?: number;
				_type: 'block';
				_key: string;
		  }
		| {
				_key: string;
				_type: 'code';
				language?: string;
				filename?: string;
				code?: string;
				highlightedLines?: Array<number>;
		  }
		| {
				asset?: SanityImageAssetReference;
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				alt?: string;
				caption?: string;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'image';
				_key: string;
				width: number | null;
				height: number | null;
				color: string | null;
		  }
		| {
				_key: string;
				_type: 'table';
				rows?: Array<
					{
						_key: string;
					} & TableRow
				>;
		  }
		| {
				file?: {
					asset?: SanityFileAssetReference;
					media?: unknown;
					_type: 'file';
				};
				poster: {
					asset: SanityImageAssetReference | null;
					width: number | null;
					height: number | null;
				} | null;
				caption?: string;
				alt?: string;
				autoplay?: boolean;
				loading?: 'eager' | 'lazy';
				layout?: 'full-width' | 'text-width';
				_type: 'video';
				_key: string;
				url: string | null;
		  }
		| {
				url?: string;
				layout?: 'full-width' | 'text-width';
				_type: 'videoEmbed';
				_key: string;
		  }
	> | null;
}>;

// Source: ../frontend/src/app/sitemap.ts
// Variable: sitemapQuery
// Query: *[_type == "post"] {			_updatedAt,			slug,		}
export type SitemapQueryResult = Array<{
	_updatedAt: string;
	slug: Slug | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'\n\t\t*[_type == "post" && slug.current == $slug][0] {\n\t\t\ttitle,\n\t\t\tdescription,\n\t\t\tslug,\n\t\t\timage { \n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n }\n\t\t}\n\t': PostMetadataQueryResult;
		'\n\t\t*[_type == "post" && slug.current == $slug][0] {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\tbody[] {\n\t\t...,\n\t\t_type == \'image\' => {\n\t\t\t...,\n\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t"color": asset->metadata.palette.dominant.background,\n\t\t},\n\t\t_type == \'video\' => {\n\t\t\t...,\n\t\t\t"url": file.asset->url,\n\t\t\tposter {\n\t\t\t\tasset,\n\t\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t},\n\t\t},\n\t}\n\n\t\t}\n\t': PostPageQueryResult;
		'\n\t\t*[_type == "post" && slug.current != $slug && type == $type][0...16] | order(meta.date desc, _createdAt desc) {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\n\t\t}\n\t': PostPageOtherPostsQueryResult;
		'\n\t\t*[_type == "post"] { slug }\n\t': PostsStaticParamsQueryResult;
		'\n\t\t*[_type == "post" && type != "page"][0...16] | order(_createdAt desc) {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\tbody[] {\n\t\t...,\n\t\t_type == \'image\' => {\n\t\t\t...,\n\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t"color": asset->metadata.palette.dominant.background,\n\t\t},\n\t\t_type == \'video\' => {\n\t\t\t...,\n\t\t\t"url": file.asset->url,\n\t\t\tposter {\n\t\t\t\tasset,\n\t\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t},\n\t\t},\n\t}\n\n\t\t}\n\t': FeedQueryResult;
		'\n\t\t*[_type == "post" && type == "artwork"] | order(meta.date desc, _createdAt desc) {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\n\t\t}\n\t': ArtworksPageQueryResult;
		'\n\t\t*[_type == "navigation"][0]\n\t': NavigationQueryResult;
		'\n\t\t*[_type == "settings"][0] { socialMedia }\n\t': LayoutSettingsQueryResult;
		'\n\t\t*[_type == "settings"][0] {\n\t\t\twebsiteName,\n\t\t\tdescription,\n\t\t}\n\t': HomeMetadataQueryResult;
		'\n\t\t*[_type == "settings"][0] {\n\t\t\tintroMessage\n\t\t}\n\t': HomeSettingsQueryResult;
		'\n\t\t*[_type == "post" && type == "artwork"][0...16] | order(meta.date desc, _createdAt desc) {\n\t\t\t\n\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\n\t"thumbnailVideoUrl": thumbnailVideo.asset->url,\n\n\t\t}\n\t': HomeArtworksQueryResult;
		'\n\t\t*[_type == "post" && type == "article"][0...16] | order(meta.date desc, _createdAt desc) {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\n\t\t}\n\t': HomePostsQueryResult;
		'\n\t\t*[_type == "post" && type == "project"][0...16] | order(meta.date desc, _createdAt desc) {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\n\t\t}\n\t': HomeProjectsQueryResult;
		'\n\t\t*[_type == "post" && type == "project"] | order(meta.date desc, _createdAt desc) {\n\t\t\t\n\t...,\n\timage {\n\t\t\n\tasset,\n\talt,\n\t"width": asset->metadata.dimensions.width,\n\t"height": asset->metadata.dimensions.height,\n\t"color": asset->metadata.palette.dominant.background,\n\n\t},\n\tbody[] {\n\t\t...,\n\t\t_type == \'image\' => {\n\t\t\t...,\n\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t"color": asset->metadata.palette.dominant.background,\n\t\t},\n\t\t_type == \'video\' => {\n\t\t\t...,\n\t\t\t"url": file.asset->url,\n\t\t\tposter {\n\t\t\t\tasset,\n\t\t\t\t"width": asset->metadata.dimensions.width,\n\t\t\t\t"height": asset->metadata.dimensions.height,\n\t\t\t},\n\t\t},\n\t}\n\n\t\t}\n\t': ProjectsPageQueryResult;
		'\n\t\t*[_type == "post"] {\n\t\t\t_updatedAt,\n\t\t\tslug,\n\t\t}\n\t': SitemapQueryResult;
	}
}
